-- Search Request log table

CREATE TABLE [dbo].[SearchLogs]
(
	[ID]			INT IDENTITY (1, 1)	NOT NULL,
	[TIMESTAMP]		DATETIME			NOT NULL,
	[REQUESTTYPE]	NVARCHAR (100)		NOT NULL,
	[CLIENTIP]		NVARCHAR (100)		NOT NULL,
	[BROWSER]		NVARCHAR (100)		NOT NULL

	CONSTRAINT [PK_dbo.SearchLogs] PRIMARY KEY CLUSTERED ([ID] ASC)
);